import type { Course } from '@/types'

export const COURSES: Course[] = [
  {
    id: 1, path_id: 1, slug: 'bhagavad-gita-essentials',
    emoji: '📖', bg_color: '#1a0a00',
    title_en: 'Bhagavad Gita Essentials', title_te: 'భగవద్గీత తత్వం',
    description_en: 'Explore the timeless wisdom of the Bhagavad Gita — 18 chapters decoded for modern life. Learn about dharma, karma, and the path to liberation through Lord Krishna\'s teachings.',
    description_te: 'భగవద్గీత యొక్క కాలాతీత జ్ఞానాన్ని అన్వేషించండి — ఆధునిక జీవితానికి అనువదించిన 18 అధ్యాయాలు.',
    instructor_en: 'Swami Ramananda', instructor_te: 'స్వామి రామానంద',
    category: 'Bhagavad Gita', level: 'Beginner',
    duration: '18h', is_free: false, price: 799,
    rating: 4.9, review_count: 234, student_count: 1847,
    has_quiz: false, order_index: 1, is_published: true,
    curriculum: [
      'Understanding the battlefield of Kurukshetra', 'Karma Yoga — the path of selfless action',
      'Bhakti Yoga — devotion as a spiritual path', 'Jnana Yoga — wisdom and knowledge',
      'The nature of the eternal soul (Atman)', 'Liberation and the ultimate goal of life',
    ],
  },
  {
    id: 2, path_id: 1, slug: 'vedic-mantra-chanting',
    emoji: '🕉', bg_color: '#001a0a',
    title_en: 'Vedic Mantra Chanting', title_te: 'వేద మంత్ర పఠనం',
    description_en: 'Learn the art of Vedic mantra chanting with proper pronunciation, rhythm, and meaning. This course covers Gayatri mantra, Om chanting, and key Vedic hymns.',
    description_te: 'సరైన ఉచ్చారణ, లయ మరియు అర్థంతో వేద మంత్ర పఠన కళను నేర్చుకోండి.',
    instructor_en: 'Pandit Krishnamurti', instructor_te: 'పండిట్ కృష్ణమూర్తి',
    category: 'Mantras', level: 'Beginner',
    duration: '8h', is_free: true, price: 0,
    rating: 4.8, review_count: 187, student_count: 2341,
    has_quiz: false, order_index: 2, is_published: true,
    curriculum: [
      'Introduction to Vedic phonetics', 'Gayatri Mantra — the mother of all mantras',
      'Om and its significance in meditation', 'Mahamrityunjaya Mantra for healing',
      'Morning and evening Vedic prayers', 'Building a daily chanting practice',
    ],
  },
  {
    id: 3, path_id: 1, slug: 'upanishads-inner-light',
    emoji: '🪔', bg_color: '#150010',
    title_en: 'Upanishads: Inner Light', title_te: 'ఉపనిషత్తులు: అంతరంగ జ్యోతి',
    description_en: 'Journey into the philosophical depths of the Upanishads. Explore concepts of Brahman, Atman, and non-duality (Advaita) through classical texts.',
    description_te: 'ఉపనిషత్తుల తాత్విక లోతులలో ప్రయాణం చేయండి. బ్రహ్మం, ఆత్మ మరియు అద్వైతాన్ని అన్వేషించండి.',
    instructor_en: 'Dr. Venkateswara Rao', instructor_te: 'డా. వెంకటేశ్వర రావు',
    category: 'Upanishads', level: 'Advanced',
    duration: '24h', is_free: false, price: 1199,
    rating: 4.7, review_count: 89, student_count: 623,
    has_quiz: false, order_index: 3, is_published: true,
    curriculum: [
      'Mandukya Upanishad — states of consciousness', 'Kena Upanishad — the power behind the mind',
      'Isha Upanishad — God in all', 'Taittiriya Upanishad — five sheaths of existence',
      'Chandogya Upanishad — Tat Tvam Asi', 'Brihadaranyaka Upanishad — the great forest text',
    ],
  },
  {
    id: 4, path_id: 1, slug: 'puja-vidhi-and-rituals',
    emoji: '🌸', bg_color: '#001a0a',
    title_en: 'Puja Vidhi and Rituals', title_te: 'పూజా విధి మరియు సంప్రదాయాలు',
    description_en: 'Master traditional Hindu puja procedures, from daily home worship to festival rituals. Learn the correct methods, materials, and mantras for each ritual.',
    description_te: 'రోజువారీ గృహ పూజ నుండి పండుగ వేడుకల వరకు సంప్రదాయ హిందూ పూజా విధానాలను నేర్చుకోండి.',
    instructor_en: 'Archaka Subrahmanyam', instructor_te: 'అర్చక సుబ్రహ్మణ్యం',
    category: 'Puja & Rituals', level: 'Beginner',
    duration: '12h', is_free: false, price: 499,
    rating: 4.8, review_count: 312, student_count: 2156,
    has_quiz: false, order_index: 4, is_published: true,
    curriculum: [
      'Setting up the puja altar', 'Daily Nitya puja procedure',
      'Ganesh puja for auspicious beginnings', 'Lakshmi puja for prosperity',
      'Satyanarayana puja — complete guide', 'Festival rituals — Diwali, Navaratri & more',
    ],
  },
  {
    id: 5, path_id: 1, slug: 'yoga-and-vedic-philosophy',
    emoji: '🧘', bg_color: '#0a001a',
    title_en: 'Yoga and Vedic Philosophy', title_te: 'యోగ మరియు వేద తత్వశాస్త్రం',
    description_en: 'Understand yoga beyond asanas — explore the philosophical foundations of Patanjali\'s Yoga Sutras and their connection to Vedantic thought.',
    description_te: 'ఆసనాలకు మించి యోగను అర్థం చేసుకోండి — పతంజలి యోగ సూత్రాల తాత్విక పునాదులను అన్వేషించండి.',
    instructor_en: 'Yogacharya Prasad', instructor_te: 'యోగాచార్య ప్రసాద్',
    category: 'Yoga & Philosophy', level: 'Intermediate',
    duration: '20h', is_free: false, price: 999,
    rating: 4.9, review_count: 178, student_count: 1432,
    has_quiz: false, order_index: 5, is_published: true,
    curriculum: [
      'The eight limbs of yoga (Ashtanga)', 'Samadhi — union with the divine',
      'Pratyahara — withdrawal of the senses', 'Dharana and Dhyana — concentration and meditation',
      'Vedantic roots of yoga philosophy', 'Integrating yoga into daily life',
    ],
  },
  {
    id: 6, path_id: 1, slug: 'ramayana-for-beginners',
    emoji: '📿', bg_color: '#1a0a00',
    title_en: 'Ramayana for Beginners', title_te: 'రామాయణం - ప్రారంభకులకు',
    description_en: 'Discover the epic story of Lord Rama through Valmiki\'s original Ramayana. Learn its spiritual significance, characters, and timeless moral lessons.',
    description_te: 'వాల్మీకి రామాయణం ద్వారా శ్రీరాముని మహాకావ్య కథను కనుగొనండి.',
    instructor_en: 'Prof. Sitaram Sharma', instructor_te: 'ప్రొ. సీతారాం శర్మ',
    category: 'Ramayana', level: 'Beginner',
    duration: '16h', is_free: true, price: 0,
    rating: 4.9, review_count: 445, student_count: 3201,
    has_quiz: false, order_index: 6, is_published: true,
    curriculum: [
      'Bala Kanda — the childhood of Rama', 'Ayodhya Kanda — the royal dilemma',
      'Aranya Kanda — forest life and Sita\'s abduction', 'Kishkindha Kanda — alliance with Hanuman',
      'Sundara Kanda — Hanuman\'s journey to Lanka', 'Yuddha Kanda — the battle and victory',
    ],
  },
  {
    id: 7, path_id: 1, slug: 'shiva-purana-stories',
    emoji: '🔱', bg_color: '#1a0005',
    title_en: 'Shiva Purana Stories', title_te: 'శివ పురాణ కథలు',
    description_en: 'Explore the divine stories from the Shiva Purana — from the creation of the universe to the legends of Lord Shiva, Parvati, Ganesha, and Kartikeya.',
    description_te: 'శివ పురాణం నుండి దివ్య కథలను అన్వేషించండి — సృష్టి నుండి శివ, పార్వతి, గణేశ మరియు కార్తికేయ పురాణాల వరకు.',
    instructor_en: 'Shaiva Acharya Mahesh', instructor_te: 'శైవ ఆచార్య మహేష్',
    category: 'Puranas', level: 'Beginner',
    duration: '14h', is_free: false, price: 699,
    rating: 4.7, review_count: 134, student_count: 987,
    has_quiz: false, order_index: 7, is_published: true,
    curriculum: [
      'Who is Shiva? The cosmic destroyer and creator', 'The marriage of Shiva and Parvati',
      'Birth of Ganesha — the remover of obstacles', 'Kartikeya and the Sharavana Lake',
      'Shiva as Nataraja — the cosmic dancer', 'The twelve Jyotirlingas of India',
    ],
  },
  {
    id: 8, path_id: 1, slug: 'devi-mahatmyam',
    emoji: '🌺', bg_color: '#001a10',
    title_en: 'Devi Mahatmyam', title_te: 'దేవి మాహాత్మ్యం',
    description_en: '700 verses glorifying the Divine Mother. Study the three episodes of Devi Mahatmyam — Madhu-Kaitabha, Mahishasura, and Shumbha-Nishumbha — with commentary.',
    description_te: '700 శ్లోకాలతో దేవి మహిమను కీర్తించే దేవి మాహాత్మ్యాన్ని అధ్యయనం చేయండి.',
    instructor_en: 'Devi Upasaka Padmavathi', instructor_te: 'దేవి ఉపాసక పద్మావతి',
    category: 'Puranas', level: 'Intermediate',
    duration: '18h', is_free: false, price: 599,
    rating: 4.8, review_count: 201, student_count: 1654,
    has_quiz: false, order_index: 8, is_published: true,
    curriculum: [
      'Introduction to Shakta tradition', 'Prathama Charitra — Madhu-Kaitabha episode',
      'Madhyama Charitra — Mahishasura Mardini', 'Uttama Charitra — Shumbha-Nishumbha battle',
      'Devi Kavacham and Argala Stotram', 'Navaratri Puja using Devi Mahatmyam',
    ],
  },
  {
    id: 9, path_id: 1, slug: 'carnatic-devotional-music',
    emoji: '🎵', bg_color: '#0a1a00',
    title_en: 'Carnatic Devotional Music', title_te: 'కర్ణాటక భక్తి సంగీతం',
    description_en: 'Learn the divine art of Carnatic devotional music — explore bhajans, kritis, and keertanas by composers like Tyagaraja, Muthuswami Dikshitar, and Syama Sastri.',
    description_te: 'కర్ణాటక భక్తి సంగీతం నేర్చుకోండి — త్యాగరాజ, ముత్తుస్వామి దీక్షితర్ కీర్తనలు అన్వేషించండి.',
    instructor_en: 'Vidushi Sarada Devi', instructor_te: 'విదుషి శారదాదేవి',
    category: 'Devotional Music', level: 'Intermediate',
    duration: '30h', is_free: false, price: 1499,
    rating: 4.6, review_count: 76, student_count: 543,
    has_quiz: false, order_index: 9, is_published: true,
    curriculum: [
      'Fundamentals of Carnatic music theory', 'Tyagaraja pancharatna kritis',
      'Muthuswami Dikshitar\'s Navagraha kritis', 'Annamacharya keertanas — devotion to Venkateshwara',
      'Bhakti movement composers and their impact', 'Performing bhajans and devotional songs',
    ],
  },
  {
    id: 10, path_id: 1, slug: 'sanskrit-for-beginners',
    emoji: '📚', bg_color: '#1a0a00',
    title_en: 'Sanskrit for Beginners', title_te: 'సంస్కృతం - ప్రారంభకులకు',
    description_en: 'Learn the mother of all languages — Sanskrit. From Devanagari script to basic grammar, this course gives you the foundation to read sacred texts in the original.',
    description_te: 'అన్ని భాషల తల్లి అయిన సంస్కృతం నేర్చుకోండి. దేవనాగరి లిపి నుండి ప్రాథమిక వ్యాకరణం వరకు.',
    instructor_en: 'Acharya Vidyananda', instructor_te: 'ఆచార్య విద్యానంద',
    category: 'Sanskrit', level: 'Beginner',
    duration: '22h', is_free: false, price: 1299,
    rating: 4.8, review_count: 156, student_count: 1123,
    has_quiz: false, order_index: 10, is_published: true,
    curriculum: [
      'Devanagari script — vowels and consonants', 'Basic Sanskrit grammar — vibhaktis',
      'Simple Sanskrit sentences and vocabulary', 'Reading simple slokas and prayers',
      'Sandhi rules — joining words', 'Reading short passages from sacred texts',
    ],
  },
  {
    id: 11, path_id: 1, slug: 'jyotisha-vedic-astrology',
    emoji: '🌙', bg_color: '#0a001a',
    title_en: 'Jyotisha: Vedic Astrology', title_te: 'జ్యోతిష్యం: వేద జ్యోతిష్యం',
    description_en: 'Understand the ancient science of Jyotisha — Vedic astrology. Learn to read birth charts (kundalis), planetary influences, and apply astrological wisdom to life.',
    description_te: 'జ్యోతిష్యం యొక్క ప్రాచీన విజ్ఞానాన్ని అర్థం చేసుకోండి. జన్మ కుండలీలు చదవటం నేర్చుకోండి.',
    instructor_en: 'Jyotishi Anantacharya', instructor_te: 'జ్యోతిషి అనంతాచార్య',
    category: 'Jyotisha', level: 'Advanced',
    duration: '28h', is_free: false, price: 1899,
    rating: 4.7, review_count: 98, student_count: 712,
    has_quiz: false, order_index: 11, is_published: true,
    curriculum: [
      'Introduction to Jyotisha — the eye of the Vedas', 'The nine grahas and their significations',
      'Rashis (zodiac signs) and their qualities', 'Reading a birth chart — houses and their meanings',
      'Dashas and transits — timing life events', 'Remedies and upayams in Vedic astrology',
    ],
  },
  {
    id: 12, path_id: 1, slug: 'vastu-shastra-basics',
    emoji: '🪬', bg_color: '#001a15',
    title_en: 'Vastu Shastra Basics', title_te: 'వాస్తు శాస్త్రం - పరిచయం',
    description_en: 'Learn the ancient Indian science of architecture and spatial harmony — Vastu Shastra. Understand directional principles and how to apply them to homes and workplaces.',
    description_te: 'వాస్తు శాస్త్రాన్ని నేర్చుకోండి — ప్రాచీన భారతీయ వాస్తుశిల్పం మరియు స్థలానుకూలత విజ్ఞానం.',
    instructor_en: 'Vastu Expert Nagabhushana', instructor_te: 'వాస్తు నిపుణుడు నాగభూషణ',
    category: 'Vastu', level: 'Beginner',
    duration: '10h', is_free: true, price: 0,
    rating: 4.6, review_count: 123, student_count: 876,
    has_quiz: false, order_index: 12, is_published: true,
    curriculum: [
      'History and principles of Vastu Shastra', 'The five elements and their directions',
      'Vastu for the main entrance and living room', 'Kitchen and bedroom Vastu guidelines',
      'Vastu for pooja room placement', 'Common Vastu doshas and their remedies',
    ],
  },
]

export const STATS = {
  studentsEnrolled: 12456,
  coursesAvailable: 12,
  averageRating: 4.8,
  languages: 2,
}

export const CATEGORY_ICONS: Record<string, string> = {
  'Bhagavad Gita': '📖',
  Mantras: '🕉',
  Upanishads: '🪔',
  'Puja & Rituals': '🌸',
  'Yoga & Philosophy': '🧘',
  Ramayana: '📿',
  Puranas: '🔱',
  'Devotional Music': '🎵',
  Sanskrit: '📚',
  Jyotisha: '🌙',
  Vastu: '🪬',
}
